### ISSUE TITLE
Single endpoint performance testing

### ISSUE THREAD

**Issue by applethepeanut** [hmrc/performance-test-runner#1]
Currently we can only run full user journeys, but not single endpoints (or mixtures thereof); could you add support to re-run certain parts n times, such that one could either
- run a small part many times in isolation (no journey)
- run a specific part once, but then another part many times in the same journey, for example
  `val testEndpointAfterLogin: Seq[HttpRequestBuilder] = Seq(login, nailEndpoint10000Times)`
  where `login` is run once as a prerequisite and `nailEndpoint10000Times` is run many times (preferable configured/passed in)

I wouldn't expect this to be the API, it's just an illustration of my requirement

**Comment by ejayaraman** [comment]
A lot has changed in the library since this ticket. Closing the issue until this is being requested again.
