### ISSUE TITLE
Add support for abstract journeys

### ISSUE THREAD

**Issue by paoloboni** [hmrc/performance-test-runner#11]
Add support for abstract journeys to allow the reuse of part of the journey definition.

An abstract journey can be used to define a set of properties that can be shared across different (non-abstract) journeys. The properties needed to define an abstract journey are:
* description
* feeder
* parts

If an abstract journey definition is missing one of the properties above, an exception should be thrown.

An abstract journey must be marked as abstract by setting the property `abstract = true`.
It should look like the following:
```
base-journey = {
  abstract = true
  description = "Base journey"
  feeder = data.csv
  parts = [
    login,
    navigate-to-home,
    logout
  ]
}
```

In the definition of a journey which extents an abstract one, the reference to the abstract journey has to be declared by setting the value of the property `extends` to the abstract journey key. Below there's an example:
```
test-journey-1 = {
  extends = base-journey
  load = 5
  run-if = [label-A]
  skip-if = [label-B, label-C]
}
```

As the journey's descriptions have to be unique, the description of a journey which extends an abstract one has to be dynamically created. The resulting description is the concatenation of the abstract journey description and the run-if/skip-if values (if present).
For instance, the description of the `test-journey-1` declared above is `Base journey - run-if [label-A] and skip-if [label-B, label-C]`

**Comment by carlosgarciapuerta** [comment]
Released in performance-test-runner 1.12.0
