### ISSUE TITLE
Multiple values defined in 'run-if' should be evaluated in AND

### ISSUE THREAD

**Issue by paoloboni** [hmrc/performance-test-runner#15]
When 'run-if' has multiple values, these should be evaluated using AND operator.
The condition to run a journey is that all the `run-if` labels must be present in `labels` configuration for the performance test.

For instance:
having the following labels in the performance test configuration:
`labels = "label-A"`
and the following journey configuration:
```
test-journey = {
  description = "Test journey"
  load = 0.1
  feeder = data.csv
  parts = [
    home
  ]
  run-if = ["label-A", "label-B"]
}
```
the journey above should not be executed.

**Comment by carlosgarciapuerta** [comment]
Released in performance-test-runner 1.12.0
