### ISSUE TITLE
Cannot override feeder of an abstract journey

### ISSUE THREAD

**Issue by jakobgrunig** [hmrc/performance-test-runner#17]
I need to be able to write many journeys where the parts are always the same but the feeder changes.

**Comment by paoloboni** [comment]
The current implementation allows you to define an abstract without a feeder. Then all the journeys that extend this abstract need to have a feeder defined. Would this meet the requirement?

**Comment by jakobgrunig** [comment]
Yes, but it doesn't work.

**Comment by ejayaraman** [comment]
Abstract journeys are not being used and has been deprecated.
