### ISSUE TITLE
the statement logger might be a little confusing

### ISSUE THREAD

**Issue by funkmaster20th** [hmrc/performance-test-runner#54]
on the line

https://github.com/hmrc/performance-test-runner/blob/fede938605e40f5d2184de096f860109cadd23ba/src/main/scala/uk/gov/hmrc/performance/simulation/JourneySetup.scala#L60

we log out the loadpercentage but this is the load percentage /100 so would look like 1% load percentage, so do we remove the percentage symbol to inform the user the load is bing times by this figure or pull in the perftest.loadpecentage value instead? so would look like 100%

**Comment by vivrichards600** [comment]
This issue has just been resolved https://github.com/hmrc/performance-test-runner/pull/55
